// Single door to the back room.
//
// The prototype this replaces had two failure modes we must never repeat:
//   1. it forgot the auth token, so writes 401'd, and
//   2. it used `.then(() => setSaved(true))`, which fires on a 401 too, because
//      fetch only rejects on network errors — so the UI said "Saved ✓" while
//      saving nothing.
// Every response is therefore checked here, and anything non-2xx throws. A
// screen cannot report success unless the server actually accepted the write.

const TOKEN_KEY = 'eurostar-admin-token';

export function getToken(): string {
  try {
    return localStorage.getItem(TOKEN_KEY) || '';
  } catch {
    return '';
  }
}

export function setToken(token: string): void {
  try {
    if (token) localStorage.setItem(TOKEN_KEY, token);
    else localStorage.removeItem(TOKEN_KEY);
  } catch {
    /* storage disabled — session lasts for this page only */
  }
}

export class ApiError extends Error {
  constructor(
    message: string,
    readonly status: number
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

/** True when the session is gone and the user must sign in again. */
export function isAuthError(e: unknown): boolean {
  return e instanceof ApiError && (e.status === 401 || e.status === 403);
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  const headers: Record<string, string> = { accept: 'application/json' };
  const token = getToken();
  if (token) headers.authorization = `Bearer ${token}`;
  if (body !== undefined) headers['content-type'] = 'application/json';

  let resp: Response;
  try {
    resp = await fetch(path, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
  } catch {
    throw new ApiError('Could not reach the server. Check your connection.', 0);
  }

  const text = await resp.text();
  let data: any = null;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = text;
  }

  if (!resp.ok) {
    if (resp.status === 401 || resp.status === 403) {
      // Stale session: drop the dead token and let the shell show the login gate.
      setToken('');
      window.dispatchEvent(new Event('eurostar-auth-lost'));
    }
    const msg =
      (data && typeof data === 'object' && data.error) ||
      (resp.status === 401 ? 'Your session expired — please sign in again.' : `Request failed (${resp.status})`);
    throw new ApiError(String(msg), resp.status);
  }
  return data as T;
}

export const api = {
  get: <T>(path: string) => request<T>('GET', path),
  post: <T>(path: string, body?: unknown) => request<T>('POST', path, body ?? {}),
  put: <T>(path: string, body?: unknown) => request<T>('PUT', path, body ?? {}),
  del: <T>(path: string) => request<T>('DELETE', path),
};

// --- Types shared across screens -------------------------------------------

export type Unit = 'pc' | 'ct' | 'pkt' | 'strip';

export interface Category {
  key: string;
  name: string;
  short: string;
  blurb: string;
  unit: Unit;
  origin: string;
  skipGrade: boolean;
  count: number;
  sortOrder: number;
  hidden: boolean;
}

export interface NewCategory {
  name: string;
  short?: string;
  blurb?: string;
  unit: Unit;
  origin?: string;
  skipGrade?: boolean;
  count?: number;
}

export type StaffRole = 'rep' | 'office' | 'admin';

export interface StaffUser {
  id: string;
  role: StaffRole;
  name: string;
  username: string;
  phone: string;
  active: boolean;
  isOwner: boolean;
  createdAt: string;
}

export interface NewStaffUser {
  role: StaffRole;
  name: string;
  username: string;
  password?: string; // generated by the server when omitted
  phone?: string;
}

export interface StoreRules {
  gstRate?: number;
  courierFlat?: number;
  courierFreeOver?: number;
  minOrderValue?: number;
  dispatchWorkingDays?: number;
  exportDispatchDays?: number;
  rfqMinValue?: number;
  defaultPayment?: string;
  languages?: string[];
  inviteOnly?: boolean;
  watermarkPriceSheets?: boolean;
  noindex?: boolean;
}

export interface SiteContent {
  heroTitle?: string;
  heroSub?: string;
  footerNote?: string;
  businessHours?: string;
  testimonials?: { id: string; name: string; text: string; city?: string }[];
}

export interface Product {
  id: string;
  name: string;
  cat: string;
  tone: string;
  shape: string;
  size: string;
  clarity: string;
  price: number;
  unit: string;
  moq: number;
  stock: 'in' | 'low' | 'out';
  stockCount: number;
  badge: string | null;
  desc: string | null;
  hidden: boolean;
}

export interface BulkResult {
  received: number;
  created: number;
  updated: number;
}

// Catalogue overlays, all keyed by Category.key.
// Shapes match what the storefront already reads — see docs/app/data.jsx
// (GRADES_BY_CATEGORY) and docs/app/product-images.jsx.
export interface Grade {
  id: string;
  name: string;
  tier?: string;
  origin?: string;
  desc?: string;
  tone?: string;
  basePrice?: number;
  unit?: string;
}
export type GradesByCat = Record<string, Grade[]>;

export interface Colour {
  id: string;
  name: string;
  hex?: string;
}
export type ColoursByCat = Record<string, Colour[]>;
export type ShapesByCat = Record<string, string[]>;

/** Product photo map. Key format is fixed by the storefront: `cat|colour|shape`. */
export type ProductImages = Record<string, string>;
export const productImageKey = (cat: string, colour: string, shape: string) => `${cat}|${colour}|${shape}`;

export interface Announcement {
  active: boolean;
  image: string | null;
  title: string | null;
  message: string | null;
  badge: string | null;
}

export const adminApi = {
  login: (username: string, password: string, remember: boolean) =>
    api.post<{ accessToken: string; name?: string }>('/auth/login', {
      role: 'admin',
      username,
      password,
      remember,
    }),

  categories: () => api.get<Category[]>('/admin/catalog/categories'),
  createCategory: (c: NewCategory) => api.post<Category>('/admin/catalog/categories', c),
  updateCategory: (key: string, patch: Partial<Category>) =>
    api.put<Category>(`/admin/catalog/categories/${encodeURIComponent(key)}`, patch),
  deleteCategory: (key: string) => api.del<{ deleted: string }>(`/admin/catalog/categories/${encodeURIComponent(key)}`),

  rules: () => api.get<StoreRules>('/admin/settings/rules'),
  saveRules: (r: StoreRules) => api.put<StoreRules>('/admin/settings/rules', r),

  content: () => api.get<SiteContent>('/admin/content'),
  saveContent: (c: SiteContent) => api.put<SiteContent>('/admin/content', c),

  splash: () => api.get<{ image: string | null; active: boolean }>('/admin/splash'),
  saveSplash: (s: { image?: string | null; active?: boolean }) => api.put('/admin/splash', s),

  catThumbs: () => api.get<Record<string, string>>('/admin/thumbs/categories'),
  saveCatThumbs: (m: Record<string, string>) => api.put('/admin/thumbs/categories', m),
  shapeThumbs: () => api.get<Record<string, string>>('/admin/thumbs/shapes'),
  saveShapeThumbs: (m: Record<string, string>) => api.put('/admin/thumbs/shapes', m),

  productImages: () => api.get<ProductImages>('/admin/product-images'),
  saveProductImages: (m: ProductImages) => api.put('/admin/product-images', m),

  grades: () => api.get<GradesByCat>('/admin/catalog/grades'),
  saveGrades: (m: GradesByCat) => api.put<GradesByCat>('/admin/catalog/grades', m),
  colours: () => api.get<ColoursByCat>('/admin/catalog/colours'),
  saveColours: (m: ColoursByCat) => api.put<ColoursByCat>('/admin/catalog/colours', m),
  shapes: () => api.get<ShapesByCat>('/admin/catalog/shapes'),
  saveShapes: (m: ShapesByCat) => api.put<ShapesByCat>('/admin/catalog/shapes', m),

  setSoldOut: (key: string, soldOut: boolean) => api.put('/inventory/admin', { key, soldOut }),

  // Staff accounts. Create/reset return the plaintext password exactly once —
  // it is never readable again, so the screen must show it there and then.
  users: () => api.get<StaffUser[]>('/users'),
  createUser: (u: NewStaffUser) => api.post<StaffUser & { password?: string }>('/users', u),
  updateUser: (id: string, patch: Partial<Pick<StaffUser, 'name' | 'phone' | 'role' | 'active'>>) =>
    api.put<StaffUser>(`/users/${encodeURIComponent(id)}`, patch),
  resetPassword: (id: string) =>
    api.post<{ id: string; username: string; password: string }>(`/users/${encodeURIComponent(id)}/reset-password`),
  deleteUser: (id: string) => api.del<{ deleted?: string }>(`/users/${encodeURIComponent(id)}`),

  products: (cat?: string) => api.get<Product[]>(`/admin/products${cat ? `?cat=${encodeURIComponent(cat)}` : ''}`),
  updateProduct: (id: string, patch: Partial<Product>) =>
    api.put<Product>(`/admin/products/${encodeURIComponent(id)}`, patch),
  createProduct: (p: Partial<Product> & { id: string; name: string; cat: string; price: number }) =>
    api.post<Product>('/admin/products', p),
  deleteProduct: (id: string) => api.del<{ deleted: string }>(`/admin/products/${encodeURIComponent(id)}`),
  bulkProducts: (products: unknown[]) => api.post<BulkResult>('/admin/products/bulk', { products }),

  announcement: () => api.get<Announcement>('/announcements'),
  saveAnnouncement: (a: Partial<Announcement>) => api.put<Announcement>('/announcements', a),
};

/** Read a picked file as a data URL, which is how images are stored. */
export function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = () => reject(new Error('Could not read that file.'));
    r.readAsDataURL(file);
  });
}
