// Shape id -> display name. Generated from docs/app/data.jsx SHAPES.
export const SHAPE_NAMES: Record<string, string> = {
  "round": "Round",
  "oval": "Oval",
  "pear": "Pear",
  "emerald": "Emerald",
  "radiant": "Radiant",
  "marquise": "Marquise",
  "princess": "Princess",
  "cushion": "Cushion",
  "asscher": "Asscher",
  "heart": "Heart",
  "trillion": "Trillion",
  "baguette": "Baguette",
  "tapered": "Tapered Baguette",
  "octagon-step": "Octagon Step",
  "octagon-princess": "Octagon Princess",
  "oblong-cushion": "Oblong Cushion",
  "curved-trillion": "Curved Trillion",
  "fulldrilled": "Full Drilled",
  "halfdrilled": "Half Drilled",
  "undrilled": "Undrilled",
  "cabs": "Cabs",
  "square": "Square",
  "cube": "Cube",
  "pearoval": "Pear / Oval",
  "cabochon": "Cabochon",
  "clover": "Clover",
  "shell": "Shell",
  "bellflower": "Bell Flower",
  "bulgari": "Bulgari Motif",
  "cutstones": "Cut Stones",
  "maniya": "Maniya",
  "tyre-plain": "Tyre Beads (Batti) · Plain",
  "tyre-fac": "Tyre Beads (Batti) · Faceted",
  "ballhole-plain": "Ball with Hole · Plain",
  "ballhole-fac": "Ball with Hole · Faceted",
  "plain-beads": "Plain Beads",
  "faceted-beads": "Faceted Beads",
  "oval-maniya": "Oval Maniya",
  "drops": "Drops",
  "butterfly": "Butterfly",
  "flower5": "5-Petal Flower",
  "star": "Star",
  "palm": "Palm",
  "round-cabs": "Round Cabs",
  "oval-cabs": "Oval Cabs",
  "pear-cabs": "Pear Cabs",
  "marquise-cabs": "Marquise Cabs",
  "square-cabs": "Square Cabs",
  "undrilled-ball": "Undrilled Ball",
  "drilled-ball": "Drilled Ball",
  "dholki": "Dholki",
  "tile": "Tile",
  "triangle": "Triangle",
  "oblong": "Oblong Cushion",
  "hexagon": "Hexagon",
  "long-hexa": "Long Hexagon",
  "tarpozid": "Trapezoid",
  "kite": "Kite",
  "uneven": "Uneven Polki"
};
